# Databricks notebook source
print("Hello world")
print("Good morning")
print("Hello India")
print("the UK")
print("canada")
print("hello mexico")
print("asia")
print("europe")
print("hello america")
print("hello worldd")
print("hello")
print("how are you")
